// Code generated by sqlc. DO NOT EDIT.
// source: user.sql

package db

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  firstname,
  lastname,
  birth_date,
  email,
  password
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, firstname, lastname, birth_date, email, password, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Firstname string    `json:"firstname"`
	Lastname  string    `json:"lastname"`
	BirthDate time.Time `json:"birth_date"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Users, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Firstname,
		arg.Lastname,
		arg.BirthDate,
		arg.Email,
		arg.Password,
	)
	var i Users
	err := row.Scan(
		&i.ID,
		&i.Firstname,
		&i.Lastname,
		&i.BirthDate,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
